services:
  - type: web
    name: django-backend
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend_livros.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: django-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString

databases:
  - name: django-db
